batch_size: 64
checkpoints: 5
config_path: null
data_dir: datasets/
dataset_name: cifar10
epochs: 10
gamma: 0.1
gpu: true
log_interval: 1
logger: null
lr: 0.1
lr_scheduler: null
model: resnet34
model_dir: checkpoints/
momentum: 0.9
nesterov: false
num_workers: 8
optimizer: AdamW
pretrained: false
save_model: true
seed: 1
shuffle: false
steps_list: null
val_batch_size: 1000
val_phase: true
weight_decay: 0.01
